# Generated by Django 3.1.4 on 2020-12-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('maxscore', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='date submitted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pydump.profile')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pydump.problem')),
            ],
        ),
    ]
