# Generated by Django 3.1.4 on 2020-12-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0002_auto_20201224_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
