# Generated by Django 3.1.4 on 2020-12-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0003_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
