# Generated by Django 3.1.4 on 2020-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0004_auto_20201226_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
