# Generated by Django 3.1.4 on 2020-12-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0005_question_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
