# Generated by Django 3.1.4 on 2021-01-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0009_auto_20210104_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discussion',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
