# Generated by Django 3.1.4 on 2021-01-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
