# Generated by Django 3.1.4 on 2021-01-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0012_auto_20210109_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='cmt',
        ),
    ]
