# Generated by Django 3.1.4 on 2021-01-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0013_auto_20210109_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cmt',
            new_name='content',
        ),
    ]
