# Generated by Django 3.1.4 on 2021-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0014_auto_20210109_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_0',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_8',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_9',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_0',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_8',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_9',
            field=models.TextField(default=''),
        ),
    ]
