# Generated by Django 3.1.4 on 2021-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0016_problem_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
