# Generated by Django 3.1.4 on 2021-01-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0017_auto_20210111_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
