# Generated by Django 3.1.4 on 2021-01-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0018_submission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='runtime_result',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='test_result',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
