# Generated by Django 3.1.4 on 2021-01-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0021_submission_test_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='test_count',
            field=models.IntegerField(default=10),
        ),
    ]
