# Generated by Django 3.1.4 on 2021-01-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydump', '0022_auto_20210112_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='test_count',
            field=models.IntegerField(),
        ),
    ]
